### ISSUE TITLE
feat: separate database per contract

### ISSUE THREAD

**Issue by ppedziwiatr** [warp-contracts/warp-contracts-lmdb#3]
https://github.com/kriszyp/lmdb-js#dbopendbdatabase-stringnamestring

Currently the cache in lmdb is organized in a flat structure - `contractTxId|sortKey`.
It would be better to open a separate database per contract - or keep each contract in a separate file/"root" database

**Comment by janekolszak** [comment]
I made a simple benchmark and it turns out that:

- There's no API for getting all databases in env, we'd have to store contract ids in a separate database
- **Many dbs are consume 20x more space**, e.g. 100k contracts single db takes 18MB, many 400MB
- **It takes 4x longer to insert in to manydbs**, eg. many dbs 0.2ms, single db 0.05ms

All tests are with only one interaction per contract (each db contained 1 element) 

![ManyDB - Cache size](https://user-images.githubusercontent.com/3087849/205302537-9f3b0f3b-ad60-4430-ae65-c3c643526dbf.png)
![SingleDB - Cache size](https://user-images.githubusercontent.com/3087849/205302560-574a6bcf-ab4a-4b45-b9c9-3e33e85d3646.png)
![ManyDB - Average Contract Creation Time](https://user-images.githubusercontent.com/3087849/205302623-57626b14-8659-42b0-9c60-8648c59adf48.png)
![SingleDB - Average Contract Creation Time](https://user-images.githubusercontent.com/3087849/205302628-72b2ef2f-a8ea-4b62-a48f-35761e892fb3.png)
